global using System.Diagnostics;
global using System.Runtime.InteropServices.JavaScript;
global using System.Text.Json;
global using Microsoft.AspNetCore.Components;
global using Microsoft.JSInterop;
global using TimeTracker.Rcl.Extensions;
global using TimeTracker.Shared;
global using TimeTracker.Shared.Models;
global using TimeTracker.Shared.Services;
